version: '3'

services:
  esmax:
    image: registry.gitlab.com/latamig/cl-esmax/esmaxws:0.1
    ports:
      - 8000:8000
    env_file:
    - development.env
  db:
    image: mysql:5.7
    volumes:
     - /var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=esmax
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root