# Generated by Django 2.1 on 2019-01-29 20:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('origin_url', models.URLField()),
                ('title', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('update_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Formats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('engine', models.IntegerField(choices=[(1, 'Aceite de Motores Gasolineros '), (2, 'Aceite de Motores Diesel'), (3, 'Aceite Transmisión'), (4, 'Aceites Hidraulicos'), (5, 'Aceites de Motor a Gas'), (6, 'Refrigerantes'), (7, 'Especialidades Automotrices'), (8, 'Grasas'), (9, 'Aceite Industriales')], default=1)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('pdf', models.URLField(blank=True, null=True)),
                ('mobil', models.CharField(blank=True, max_length=100, null=True)),
                ('shell_helix', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.CharField(blank=True, max_length=100, null=True)),
                ('ypf', models.CharField(blank=True, max_length=100, null=True)),
                ('texaco', models.CharField(blank=True, max_length=100, null=True)),
                ('castrol', models.CharField(blank=True, max_length=100, null=True)),
                ('valvoline', models.CharField(blank=True, max_length=100, null=True)),
                ('formats', models.ManyToManyField(related_name='formats', to='webservice.Formats')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(max_length=250)),
                ('update_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleManufacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('remote_code', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('update_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('vehicle_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webservice.VehicleCategory')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('remote_code', models.CharField(max_length=50)),
                ('update_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('vehicle_manufacture', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webservice.VehicleManufacture')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('remote_code', models.CharField(max_length=50)),
                ('update_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webservice.VehicleModel')),
            ],
        ),
        migrations.AddField(
            model_name='productrelation',
            name='car_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webservice.VehicleCategory'),
        ),
        migrations.AddField(
            model_name='productrelation',
            name='car_manufacture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webservice.VehicleManufacture'),
        ),
        migrations.AddField(
            model_name='productrelation',
            name='car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webservice.VehicleModel'),
        ),
        migrations.AddField(
            model_name='productrelation',
            name='car_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webservice.VehicleType'),
        ),
        migrations.AddField(
            model_name='productrelation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webservice.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='uses',
            field=models.ManyToManyField(related_name='uses', to='webservice.Uses'),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='vehicle_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webservice.VehicleCategory'),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='vehicle_manufacture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webservice.VehicleManufacture'),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='vehicle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webservice.VehicleModel'),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webservice.VehicleType'),
        ),
    ]
